name: couchdb
description: CouchDB client written in Dart
version: 0.7.1
homepage: https://github.com/YevhenKap/couchdb_dart
license: MIT

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.1
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0