name: couchdb
description: Library for interacting with CouchDB.
version: 0.0.1
homepage: https://github.com/YevhenKap/couchdb_dart
author: Kapelianovych Yevhen <zhenja.96.lemok@ukr.net>
license: MIT

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.0.0
