name: couchdb
description: Library for interacting with CouchDB from both a server and browser environment
version: 0.1.0
homepage: https://github.com/YevhenKap/couchdb_dart
author: Kapelianovych Yevhen <zhenja.96.lemok@ukr.net>
license: MIT

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0

dev_dependencies:
  # test: ^1.5.1
